### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by shane-riley** [mmorse1217/lean-vtk#5]
When `lean-vtk` is included as a git submodule and a CMake subdirectory, the build results from `lean-vtk` land in the `lib` and `bin` folders in the submodule's source tree. From the perspective of the user using `lean-vtk` as a submodule, it would be helpful to include a `.gitignore` file that prevents these results from being tracked with the following lines
```
/build/
/bin/
/lib/
```

**Comment by mmorse1217** [comment]
Closed by #6; thanks for the contribution!
